# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
  title: Kendrick Says
  baseurl: "/kendrick-says" # the subpath of your site, e.g. /blog
  url:  http://xander-adkins.github.io # the base hostname & protocol for your site
  # permalink: /:categories/:title/
  description: > # this means to ignore newlines until "baseurl:"
    Kendrick says, set to a curated selection of Google Fonts.
  author:
      name: "Alexander Adkins"
      email: "hello@alexanderadkins.com"
      website: "http://xander-adkins.github.io/kendrick-says/"
      twitter: xander_adkins
      github: xander-adkins
  img: /assets

  # Build settings
  markdown: kramdown

  sass:
      sass_dir: _sass
      style: :compressed
